require 'test/unit'
require './test/test_case'
require './location'
require './location_builder'
require './image_file'
require './file_helper'
# require './qr_decoder'

require './google_maps_service'
require './google_chart_service'
