source 'https://rubygems.org'

# Environment...
gem 'rails', '3.2.11'
gem 'mysql2'

# View...
gem 'haml-rails'
gem 'jquery-rails'
gem 'twitter-bootstrap-rails' #, :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'bootstrap-datepicker-rails' #,  :require => 'bootstrap-datepicker-rails', :git => 'git://github.com/Nerian/bootstrap-datepicker-rails.git'
gem 'jquery-datatables-rails' #, git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem 'i18n-js'
gem 'nested_form'
gem 'bootstrap-select-rails'

# Security...
gem 'devise'
gem 'devise-i18n'
gem 'cancan'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'tlsmail'
gem 'thin'
gem 'hpricot'
gem 'ruby_parser'

# Test...
group :development, :test do
  gem 'mocha', :require => false
  gem 'factory_girl_rails'
  gem 'headless'
  gem 'capybara'
  gem 'selenium-webdriver', '2.32.1'
  # To use debugger...
  gem 'debugger'
  gem 'hirb'
  gem 'sqlite3'
end

# User custom nonosoft library...
gem 'core', path: "core"

# ------------------------
# Fix tlsmail gem error...
# ------------------------------------------------------------------------------
require 'net/smtp'
Net.instance_eval {remove_const :SMTPSession} if defined?(Net::SMTPSession)
require 'net/pop'
Net::POP.instance_eval {remove_const :Revision} if defined?(Net::POP::Revision)
Net.instance_eval {remove_const :POP} if defined?(Net::POP)
Net.instance_eval {remove_const :POPSession} if defined?(Net::POPSession)
Net.instance_eval {remove_const :POP3Session} if defined?(Net::POP3Session)
Net.instance_eval {remove_const :APOPSession} if defined?(Net::APOPSession)
# ------------------------------------------------------------------------------

gem 'rename'
gem 'json'
