source 'https://rubygems.org'

# Environment...

ruby '2.0.0'
gem 'rails', '4.0.2'
gem 'mysql2'

# View...
gem 'haml-rails'
gem 'jquery-rails'
gem 'bootstrap-datetimepicker-rails'
gem 'bootstrap-datepicker-rails' #,	:require => 'bootstrap-datepicker-rails', :git => 'git://github.com/Nerian/bootstrap-datepicker-rails.git'
gem 'jquery-datatables-rails' #, git: 'git://github.com/rweng/jquery-datatables-rails.git'
gem 'i18n-js'
gem 'nested_form'
gem "twitter-bootstrap-rails"
gem "paperclip"

# Security...
gem 'protected_attributes'
gem 'devise', '3.0.4'
gem 'devise-i18n'
gem 'cancan'

# Gems used only for assets and not required
# in production environments by default.
#group :assets do
gem "therubyracer"
gem "less-rails"
gem 'sass-rails',	 '4.0.1'
gem 'coffee-rails', '4.0.1'
gem 'uglifier', '2.4.0'
#end

gem 'tlsmail'
gem 'thin'
gem 'hpricot'
gem 'ruby_parser'

# Dev and Test...
group :development, :test do
	gem 'pry-debugger'
	gem 'pry-rails'
	gem 'pry-plus'
	gem 'pry-debundle'
	gem 'awesome_print'
	gem "mocha", "0.14.0", require: false
	gem 'factory_girl_rails'
	gem 'headless'
	gem 'selenium-webdriver', '2.39.0'
	gem 'sqlite3'
end

# User custom nonosoft library...
gem 'core', path: "core"

gem 'workflow'
gem 'rename'
gem 'json'

gem 'rufus-scheduler'
gem "tire", :git => "git://github.com/karmi/tire.git"

# ------------------------
# Fix tlsmail gem error...
# ------------------------------------------------------------------------------
require 'net/smtp'
Net.instance_eval {remove_const :SMTPSession} if defined?(Net::SMTPSession)
require 'net/pop'
Net::POP.instance_eval {remove_const :Revision} if defined?(Net::POP::Revision)
Net.instance_eval {remove_const :POP} if defined?(Net::POP)
Net.instance_eval {remove_const :POPSession} if defined?(Net::POPSession)
Net.instance_eval {remove_const :POP3Session} if defined?(Net::POP3Session)
Net.instance_eval {remove_const :APOPSession} if defined?(Net::APOPSession)
# ------------------------------------------------------------------------------
