app:
  version: '0.9.28'
  admin_mail: 'adrianmarino@gmail.com'

mailer:
  password: 'Elnonocapo'

scheduler:
  appointment_genetator_task_time: '40 0 * * *'

log_path:
  development: './log/development.log'
  production: './log/production.log'

search_engine:
  plugin_url: 'http://siim:pa12SS@searchengine.nonosoft.com.ar/_plugin'
  highlight:
    begin: "<strong class=\"highlight\">"
    end: "</strong>"