app:
  version: '0.8.9.0'
search:
  highlight:
    begin: "<strong class=\"highlight\">"
    end: "</strong>"
mailer:
  password: 'Elnonocapo'
scheduler:
  appointment_genetator_task_time: '40 0 * * *'