app:
  version: '0.9.7'

mailer:
  password: 'Elnonocapo'

scheduler:
  appointment_genetator_task_time: '40 0 * * *'

log_path:
  development: './log/development.log'
  production: './log/production.log'

search_engine:
  user:
    username: 'siim'
    password: 'pa12SS'
  highlight:
    begin: "<strong class=\"highlight\">"
    end: "</strong>"